### ISSUE TITLE
BOM error, ATtiny

### ISSUE THREAD

**Issue by oesvends** [Duet3D/SmartEffector#1]
Hi,
I manufactured a set of PCBs for the Smarteffector 2.0, and when mounting the ATtiny44-MMH, I see that the PCB layout is intended for the ATTiny44-MU (4x4mm package) and not the MMH-version (3.1x3.1) package.

The Schematic should be fixed, IMO.  

Regards, and thanks.

**Comment by T3P3** [comment]
latest commit (https://github.com/Duet3D/SmartEffector/commit/0d208e377e57fa8604e8f18ab95525f88173d331) resolves this, thanks for point it out.
